version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: rtl-schedule-web

  mqtt-publisher:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: rtl-schedule-mqtt-publisher
    environment:
      - STOP_CODE=${STOP_CODE}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT-1883}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: always
