services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: rtl-schedule-web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  mqtt-publisher:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: rtl-schedule-mqtt-publisher
    depends_on:
      web:
        condition: service_healthy
    environment:
      - STOP_CODE=${STOP_CODE}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT-1883}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_USE_TLS=${MQTT_USE_TLS-false}
      - HASS_DISCOVERY_ENABLED=${HASS_DISCOVERY_ENABLED-false}
      - HASS_DISCOVERY_PREFIX=${HASS_DISCOVERY_PREFIX-homeassistant}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
